function LoadEnglishCombatLogs()
    DEFAULT_CHAT_FRAME:AddMessage("EnglishCombatLogs loaded.")
    COMBATHITABSORBOTHEROTHER = "%s hits %s for %d (%d absorbed).";
    COMBATHITABSORBOTHERSELF = "%s hits you for %d (%d absorbed).";
    COMBATHITABSORBSELFOTHER = "You hit %s for %d (%d absorbed).";
    COMBATHITCRITOTHEROTHER = "%s crits %s for %d.";
    COMBATHITCRITOTHERSELF = "%s crits you for %d.";
    COMBATHITCRITSELFOTHER = "You crit %s for %d.";
    COMBATHITOTHEROTHER = "%s hits %s for %d.";
    COMBATHITOTHERSELF = "%s hits you for %d.";
    COMBATHITSELFOTHER = "You hit %s for %d.";

    PERIODICAURADAMAGEABSORBEDOTHEROTHER = "%s suffers %d %s damage from %s's %s (%d absorbed).";
    PERIODICAURADAMAGEABSORBEDOTHERSELF = "You suffer %d %s damage from %s's %s (%d absorbed).";
    PERIODICAURADAMAGEABSORBEDSELFOTHER = "%s suffers %d %s damage from your %s (%d absorbed).";
    PERIODICAURADAMAGEABSORBEDSELFSELF = "You suffer %d %s damage from your %s (%d absorbed).";
    PERIODICAURADAMAGEOTHEROTHER = "%s suffers %d %s damage from %s's %s."; -- Bob suffers 5 frost damage from Jeff's Ice Nova.
    PERIODICAURADAMAGEOTHERSELF = "You suffer %d %s damage from %s's %s."; -- You suffer 3 frost damage from Rabbit's Ice Nova.
    PERIODICAURADAMAGESELFOTHER = "%s suffers %d %s damage from your %s."; -- Rabbit suffers 3 frost damage from your Ice Nova.
    PERIODICAURADAMAGESELFSELF = "You suffer %d %s damage from your %s.";
    PERIODICAURAHEALOTHEROTHER = "%s gains %d health from %s's %s."; -- Bob gains 10 health from Jane's Rejuvenation.
    PERIODICAURAHEALOTHERSELF = "You gain %d health from %s's %s."; -- You gain 12 health from John's Rejuvenation.
    PERIODICAURAHEALSELFOTHER = "%s gains %d health from your %s."; -- Bob gains 10 health from your Rejuvenation.
    PERIODICAURAHEALSELFSELF = "You gain %d health from %s."; -- You gain 10 health from Rejuvenation.


    SPELLCASTGOOTHER = "%s casts %s.";
    SPELLCASTGOOTHERTARGETTED = "%s casts %s on %s.";
    SPELLCASTGOSELF = "You cast %s.";
    SPELLCASTGOSELFTARGETTED = "You cast %s on %s.";
    SPELLCASTOTHERSTART = "%s begins to cast %s.";
    SPELLCASTSELFSTART = "You begin to cast %s.";
    SPELLDEFLECTEDOTHEROTHER = "%s's %s was deflected by %s.";
    SPELLDEFLECTEDOTHERSELF = "%s's %s was deflected.";
    SPELLDEFLECTEDSELFOTHER = "Your %s was deflected by %s.";
    SPELLDISMISSPETOTHER = "%s's %s is dismissed.";
    SPELLDISMISSPETSELF = "Your %s is dismissed.";
    SPELLDODGEDOTHEROTHER = "%s's %s was dodged by %s.";
    SPELLDODGEDOTHERSELF = "%s's %s was dodged.";
    SPELLDODGEDSELFOTHER = "Your %s was dodged by %s.";
    SPELLDURABILITYDAMAGEOTHEROTHER = "%s casts %s on %s's %s, durability is reduced by %d.";
    SPELLDURABILITYDAMAGEOTHERSELF = "%s casts %s on your %s, durability is reduced by %d.";
    SPELLDURABILITYDAMAGESELFOTHER = "You cast %s on %s's %s, durability is reduced by %d.";
    SPELLEVADEDOTHEROTHER = "%s's %s was evaded by %s.";
    SPELLEVADEDOTHERSELF = "%s's %s was evaded.";
    SPELLEVADEDSELFOTHER = "Your %s was evaded by %s.";
    SPELLEXTRAATTACKSOTHER = "%s gains %d extra attacks through %s."; -- Victim gains 3 extra attacks through Thrash.
    SPELLEXTRAATTACKSOTHER_SINGULAR = "%s gains %d extra attack through %s.";
    SPELLEXTRAATTACKSSELF = "You gain %d extra attacks through %s."; -- You gain 3 extra attacks through Thrash.
    SPELLEXTRAATTACKSSELF_SINGULAR = "You gain %d extra attack through %s.";
    SPELLFAILCASTOTHER = "%s fails to cast %s: %s.";
    SPELLFAILCASTSELF = "You fail to cast %s: %s.";
    SPELLFAILPERFORMOTHER = "%s fails to perform %s: %s.";
    SPELLFAILPERFORMSELF = "You fail to perform %s: %s.";
    SPELLHAPPINESSDRAINOTHER = "%s's %s loses %d happiness.";
    SPELLHAPPINESSDRAINSELF = "Your %s loses %d happiness.";
    SPELLIMMUNEOTHEROTHER = "%s's %s fails. %s is immune.";
    SPELLIMMUNEOTHERSELF = "%s's %s failed. You are immune.";
    SPELLIMMUNESELFOTHER = "Your %s failed. %s is immune.";
    SPELLINTERRUPTOTHEROTHER = "%s interrupts %s's %s.";
    SPELLINTERRUPTOTHERSELF = "%s interrupts your %s.";
    SPELLINTERRUPTSELFOTHER = "You interrupt %s's %s.";
    SPELLLOGABSORBOTHEROTHER = "%s's %s is absorbed by %s.";
    SPELLLOGABSORBOTHERSELF = "You absorb %s's %s.";
    SPELLLOGABSORBSELFOTHER = "Your %s is absorbed by %s.";
    SPELLLOGABSORBSELFSELF = "You absorb your %s.";
    SPELLLOGCRITOTHEROTHER = "%s's %s crits %s for %d.";
    SPELLLOGCRITOTHERSELF = "%s's %s crits you for %d.";
    SPELLLOGCRITSELFOTHER = "Your %s crits %s for %d.";
    SPELLLOGCRITSELFSELF = "Your %s crits you for %d.";
    SPELLLOGHITABSORBOTHEROTHER = "%s's %s hits %s for %d (%d absorbed).";
    SPELLLOGHITABSORBOTHERSELF = "%s's %s hits you for %d (%d absorbed).";
    SPELLLOGHITABSORBSELFOTHER = "Your %s hits %s for %d (%d absorbed).";
    SPELLLOGHITABSORBSELFSELF = "Your %s hits you for %d (%d absorbed).";
    SPELLLOGOTHEROTHER = "%s's %s hits %s for %d.";
    SPELLLOGOTHERSELF = "%s's %s hits you for %d.";
    SPELLLOGSELFOTHER = "Your %s hits %s for %d.";
    SPELLLOGSELFSELF = "Your %s hits you for %d.";

    VSABSORBOTHEROTHER = "%s attacks. %s absorbs all the damage.";
    VSABSORBOTHERSELF = "%s attacks. You absorb all the damage.";
    VSABSORBSELFOTHER = "You attack. %s absorbs all the damage.";
    VSBLOCKOTHEROTHER = "%s attacks. %s blocks.";
    VSBLOCKOTHERSELF = "%s attacks. You block.";
    VSBLOCKSELFOTHER = "You attack. %s blocks.";
    VSDEFLECTOTHEROTHER = "%s attacks. %s deflects.";
    VSDEFLECTOTHERSELF = "%s attacks. You deflect.";
    VSDEFLECTSELFOTHER = "You attack. %s deflects.";
    VSDODGEOTHEROTHER = "%s attacks. %s dodges.";
    VSDODGEOTHERSELF = "%s attacks. You dodge.";
    VSDODGESELFOTHER = "You attack. %s dodges.";
    VSENVIRONMENTALDAMAGE_DROWNING_OTHER = "%s is drowning and loses %d health.";
    VSENVIRONMENTALDAMAGE_DROWNING_SELF = "You are drowning and lose %d health.";
    VSENVIRONMENTALDAMAGE_FALLING_OTHER = "%s falls and loses %d health.";
    VSENVIRONMENTALDAMAGE_FALLING_SELF = "You fall and lose %d health.";
    VSENVIRONMENTALDAMAGE_FATIGUE_OTHER = "%s is exhausted and loses %d health.";
    VSENVIRONMENTALDAMAGE_FATIGUE_SELF = "You are exhausted and lose %d health.";
    VSENVIRONMENTALDAMAGE_FIRE_OTHER = "%s suffers %d points of fire damage.";
    VSENVIRONMENTALDAMAGE_FIRE_SELF = "You suffer %d points of fire damage.";
    VSENVIRONMENTALDAMAGE_LAVA_OTHER = "%s loses %d health for swimming in lava.";
    VSENVIRONMENTALDAMAGE_LAVA_SELF = "You lose %d health for swimming in lava.";
    VSENVIRONMENTALDAMAGE_SLIME_OTHER = "%s loses %d health for swimming in slime.";
    VSENVIRONMENTALDAMAGE_SLIME_SELF = "You lose %d health for swimming in slime.";
    VSEVADEOTHEROTHER = "%s attacks. %s evades.";
    VSEVADEOTHERSELF = "%s attacks. You evade.";
    VSEVADESELFOTHER = "You attack. %s evades.";
    VSIMMUNEOTHEROTHER = "%s attacks but %s is immune.";
    VSIMMUNEOTHERSELF = "%s attacks but you are immune.";
    VSIMMUNESELFOTHER = "You attack but %s is immune.";
    VSPARRYOTHEROTHER = "%s attacks. %s parries.";
    VSPARRYOTHERSELF = "%s attacks. You parry.";
    VSPARRYSELFOTHER = "You attack. %s parries.";


    COMBATHITCRITSCHOOLOTHEROTHER="%s crits %s for %d %s damage."
    COMBATHITCRITSCHOOLOTHERSELF="%s crits you for %d %s damage."
    COMBATHITCRITSCHOOLSELFOTHER="You crit %s for %d %s damage."
end

LoadEnglishCombatLogs()
